### PR TITLE
Fixes for Swift 2.0

### PR DESCRIPTION
**Pull request by tptee**
Basically just the suggested changes from the 1.2 -> 2.0 converter. enumerateTagsInRange also changed arguments a bit in the new SDK.

### CODE REVIEW

**Comment by ayanonagon** [comment]
Thanks for this PR, I was just thinking about Swift 2.0 support. I’ll take a look. :dancers:

**Comment by tptee** [comment]
@jordanekay @ayanonagon made analyze() a protocol extension on Analyzer and removed the extraneous String annotation as noted in the line comments. Let me know if anything else catches your eyes!

**Comment by tptee** [comment]
The lemmatizer test failed, looks like something's adding an empty string to the array.
screen shot 2015-06-25 at 5 23 38 pm

**Comment by tptee** [comment]
The lemmatizer test chokes on the apostrophe in "I'm." Maybe the defaults for NSLinguisticTaggerOptions changed?

**Comment by tptee** [comment]
Stumped. I compared the rawValue of the NSLinguisticTaggerOptions enums between master an my branch and they have the same value. It's like the tagger isn't even applying its given options??

**Comment by kartikshah** [comment]
This works for "We'll call you" "You shouldn't do that", but does not work for "I'm", "You're".  Do you folks think it is a bug with NSLingusticTagger?

**Comment by ayanonagon** [comment]
I had the same issue locally as well, then I pushed it up to run the tests on Travis, then the tests (without changing them) started passing. :scream: Still unsure what’s going on with the behavior or Lemmatizer.

**Comment by ayanonagon** [comment]
If anyone is curious: https://github.com/ayanonagon/Parsimmon/pull/28

**Comment by ayanonagon** [comment]
Ok so I just tried running the tests against iOS 8.3, and the tests pass. My tests were failing because they seemed to have improved the lemmatizer with iOS 9.0 so `my`’s lemma is now `i` instead of `my`. As for the whitespace, it seems like a bug with `NSLinguisticTagger` so I added filtering out empty strings.

I didn’t see these changes anywhere in the release notes for iOS 9. Maybe we are too hipster for Apple. ಠ_ಠ

**Comment by ayanonagon** [comment]
The errors that we were getting are weird and requires closer inspection, but I’m going to close out this PR since `master` already supports Swift 2. Thanks for the fun discussion!

**Pull request closed without merging**
