### PR TITLE
Introduce more Swift components

### PR DESCRIPTION
**Pull request by jordanekay**
This PR has two commits for a two-pass approach: first, add the Swift components, and their tests. Then, remove the Objective-C files we no longer need :hocho:. (The public-facing APIs between the two versions are identical.)

Since we're not pure Swift yet, we can't optimize the new Swift classes as much as I'd like since they still need to be visible to Objective-C. I'll go through and comment where we can simplify somethings—our basic analyzers can be immutable value types when it's all said and done. :raised_hands:

### CODE REVIEW

**Comment by jordanekay** [comment]
(No files were inherited from/harmed in the making of this pull request.)

**Comment by ayanonagon** [comment]
This is amazing. I’ll take a better look tonight. :eyes: Thanks for this! :octocat:

**Comment by ayanonagon** [comment]
Alright, I’m going to merge this. We can make tweaks as needed later. Love that you removed subclassing, thanks!! :smile:

**Comment by jordanekay** [comment]
:wrench: :tada:

**Pull request merged**
